version: 2

project_name: brew-potato

before:
  hooks:
    - go mod tidy

builds:
  - id: brew-ui-darwin
    main: ./main.go
    binary: brew-potato
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
  - id: brew-ui-linux
    main: ./main.go
    binary: brew-potato
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: brew-ui-darwin-archive
    ids:
      - brew-ui-darwin
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  - id: brew-ui-linux-archive
    ids:
      - brew-ui-linux
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

release:
  github:
    owner: mrSamDev
    name: brew-potato
  prerelease: auto

homebrew_casks:
  - name: brew-potato
    ids:
      - brew-ui-darwin-archive
    binaries:
      - brew-potato
    homepage: "https://github.com/mrSamDev/brew-potato"
    description: "Terminal UI for managing Homebrew packages."
    directory: Casks
    repository:
      owner: mrSamDev
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
